defaults: &defaults
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  projects_bucket: 'projects.dev.jordanell.com'
  posts_bucket: 'posts.dev.jordanell.com'

development:
  <<: *defaults

test:
  <<: *defaults
  projects_bucket: 'projects.test.jordanell.com'
  posts_bucket: 'posts.test.jordanell.com'

production:
  <<: *defaults
  projects_bucket: 'projects.jordanell.com'
  posts_bucket: 'posts.jordanell.com'
